### ISSUE TITLE
Binary output NULL field vs empty string returns "empty_field" classification

### ISSUE THREAD

**Issue by vegterj** [tsakonase/CoQAA#7] opened 2022-02-01 09:04 UTC

**Comment by tsakonase** [comment] 2022-02-01 23:20
The issue is that when feeding empty source AND empty target, we get back the tag "empty_field". 
When feeding empty source AND empty target, we should get back nothing (as this is not an error).

**Comment by keerthi-els** [comment] 2022-02-02 03:43
@tsakonase @vegterj 

This has been already fixed please verify and let me know if any changes needed.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/83961391/152089722-cdf8680f-35a4-4748-a359-991fc66fa115.png">

**Comment by vegterj** [comment] 2022-02-02 07:30
I'm still having an issue here; this scenario now returns 'mismatch' for me, which is also incorrect

**Comment by keerthi-els** [comment] 2022-02-02 10:54
@vegterj @tsakonase 
Closing this issue as it is fixed.

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/83961391/152140491-ef360330-ca17-404d-8b6e-bb7aa339b702.png">

**Closed by keerthi-els** 2022-02-02 10:54 UTC
